CREATE TABLE profissional_saude (
    id_profissional SERIAL PRIMARY KEY,
    nome VARCHAR NOT NULL,
    genero VARCHAR NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    telefone VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    bairro VARCHAR NOT NULL,
    rua VARCHAR NOT NULL,
    numero VARCHAR NOT NULL,
    complemento VARCHAR,
    cep CHAR(8) NOT NULL,
    registro_profissional VARCHAR UNIQUE NOT NULL,
    especialidade VARCHAR NOT NULL,
    cargo VARCHAR NOT NULL,
    id_unidade INT NOT NULL,
    data_criacao TIMESTAMP,
    data_atualizacao TIMESTAMP,
    CONSTRAINT fk_profissional_unidade FOREIGN KEY (id_unidade) REFERENCES unidade(id_unidade)
);
